### ISSUE TITLE
Standard website footer template

### ISSUE THREAD

**Issue by durack1** [PCMDI/assets#24]
Folks, we need to refresh the standard footer for external web pages. I've included my suggestion below, which I can write into an MD file to be embedded directly from this repo (just like the logo files we have already).

What we have:
The efforts of the authors are supported by the Regional and Global Climate Modeling Program of the United States Department of Energy's Office of Science. This work is funded by the Climate and Environmental Sciences Division of the DOE Office of Science and is performed under the auspices of the U.S. Department of Energy by Lawrence Livermore National Laboratory under contract DE-AC52-07NA27344. LLNL-WEB-812310

Could we update that to:
The work of PCMDI and results presented on this web page are supported by the Regional and Global Model Analysis (RGMA) Program within the Earth and Environmental Systems Sciences Division (EESSD) of the United States Department of Energy’s (DOE) Office of Science. This work of PCMDI is performed under the auspices of the U.S. DOE by Lawrence Livermore National Laboratory (LLNL) under contract DE-AC52-07NA27344. LLNL-WEB-812310.

Ping @lee1043 @kristinchang3 - if you guys are happy with the above, I'll add a `footer.md` to this repo.

**Comment by lee1043** [comment]
Just a note, IM number LLNL-WEB-812310 was approved for the following. 

"The review of your document, titled Coupled Model Intercomparison Project (CMIP) mean state and variability: Program for Climate Model Diagnosis and Intercomparison (PCMDI) Simulation Summaries, has been completed.  It can now be released to the audience you specified within the IM system - External Audience (Unlimited)."

I think the sea-ice interactive plot can be covered under this IM number.

**Comment by durack1** [comment]
@kristinchang3 ping!
